baseURL = 'https://blog.aruileen.fr/'
languageCode = 'fr-fr'
title = 'Aurélien S.'
timeZone = 'Europe/Paris'
dateFormat = "02 Jan 2006"
dateFormatFull = "02/01/2006"
dateFormatTime = "02 Jan 2006 15:04"
enableGitInfo = true
paginate = 10
[menu]
  [[menu.main]]
    identifier = "accueil"
    name = "Accueil"
    pageref = "/"
    weight = 1
  [[menu.main]]
    identifier = "cv"
    name = "Curriculum Vitæ"
    pageref = "/cv"
    weight = 2
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    pageref = "/articles"
    weight = 3
  [[menu.main]]
    identifier = "dev"
    name = "Dev & Stats"
    weight = 4
  [[menu.main]]
    identifier = "todo"
    name = "To-do list"
    pageref = "/pages/todo-list"
    weight = 1
    parent = "dev"
  [[menu.main]]
    identifier = "updates"
    name = "Updates"
    pageref = "/pages/updates"
    weight = 2
    parent = "dev"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2
    ordered = true

