baseURL = 'https://blog.aruileen.fr/'
languageCode = 'fr-fr'
title = 'Aurélien S.'
timeZone = 'Europe/Paris'
dateFormat = "02 Jan 2006"
dateFormatFull = "02/01/2006"
dateFormatTime = "02 Jan 2006 15:04"
enableGitInfo = true
paginate = 10
[menu]
  [[menu.main]]
    identifier = "accueil"
    name = "Accueil"
    pageref = "/"
    weight = 1
  [[menu.main]]
    identifier = "cv"
    name = "Curriculum Vitæ"
    pageref = "/cv"
    weight = 2
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    pageref = "/articles"
    weight = 3
  [[menu.main]]
    identifier = "dev"
    name = "Dev & Stats"
    weight = 4
  [[menu.main]]
    identifier = "updates"
    name = "Updates & Infos"
    pageref = "/pages/updates"
    weight = 2
    parent = "dev"
  [[menu.main]]
    identifier = "shortcodes"
    name = "Shortcodes"
    pageref = "/pages/shortcodes"
    weight = 3
    parent = "dev"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2
    ordered = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
[outputs]
    home = ["HTML", "RSS", "JSON"]
